k8s-service:
  applicationName: gruntwork-sample-app
  containerImage:
    repository: gruntwork/aws-sample-app
    tag: v0.0.4
    pull_policy: IfNotPresent

  replicaCount: 1

  containerPorts:
    http:
      port: 8443
      protocol: TCP

  service:
    type: NodePort
    ports:
      app:
        port: 8443

  ingress:
    enabled: true
    path: "'/*'"
    hosts:
      - gruntwork-sample-app-argo.gruntwork-sandbox.com
    servicePort: app
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: external
      alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80},{\"HTTPS\":443}]"
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/actions.ssl-redirect: "{\"Type\": \"redirect\", \"RedirectConfig\": { \"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
    additionalPathsHigherPriority:
      - path: "/*"
        serviceName: ssl-redirect
        servicePort: use-annotation

  envVars:
    CONFIG_APP_NAME: frontend
    CONFIG_SECRETS_DIR: /mnt/secrets

  scratchPaths:
    secrets: /mnt/secrets
